const PURCHASED_AT = "2026-07-11T20:00:00.000Z";

const originalProducts = [
  {
    brand: "Bambu Lab",
    productLine: "PLA Matte",
    materialFamily: "PLA",
    colorName: "Matte Charcoal",
    colorFamily: "Black",
    colorHex: "#343638",
    sku: "11101",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 2,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Matte",
    materialFamily: "PLA",
    colorName: "Matte Scarlet Red",
    colorFamily: "Red",
    colorHex: "#D9433F",
    sku: "11200",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Silk+",
    materialFamily: "PLA",
    colorName: "Gold",
    colorFamily: "Gold",
    colorHex: "#D7A629",
    sku: "13405",
    packaging: "With spool",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PETG Basic",
    materialFamily: "PETG",
    colorName: "Yellow",
    colorFamily: "Yellow",
    colorHex: "#F0D23A",
    sku: "30402",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Silk+",
    materialFamily: "PLA",
    colorName: "Silver",
    colorFamily: "Silver",
    colorHex: "#B8BDC4",
    sku: "13109",
    packaging: "With spool",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PETG Basic",
    materialFamily: "PETG",
    colorName: "White",
    colorFamily: "White",
    colorHex: "#F3F2EC",
    sku: "30106",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 2,
  },
  {
    brand: "Bambu Lab",
    productLine: "PETG Basic",
    materialFamily: "PETG",
    colorName: "Black",
    colorFamily: "Black",
    colorHex: "#18191A",
    sku: "30105",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Matte",
    materialFamily: "PLA",
    colorName: "Matte Lemon Yellow",
    colorFamily: "Yellow",
    colorHex: "#F2D34E",
    sku: "11400",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Matte",
    materialFamily: "PLA",
    colorName: "Matte Dark Brown",
    colorFamily: "Brown",
    colorHex: "#5B473C",
    sku: "11801",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PETG Basic",
    materialFamily: "PETG",
    colorName: "Green",
    colorFamily: "Green",
    colorHex: "#26A768",
    sku: "30502",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PETG Translucent",
    materialFamily: "PETG",
    colorName: "Clear",
    colorFamily: "Clear",
    colorHex: "#DCE8EA",
    sku: "32101",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Matte",
    materialFamily: "PLA",
    colorName: "Matte Grass Green",
    colorFamily: "Green",
    colorHex: "#51A266",
    sku: "11500",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Matte",
    materialFamily: "PLA",
    colorName: "Matte Nardo Gray",
    colorFamily: "Gray",
    colorHex: "#81878A",
    sku: "11104",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Basic",
    materialFamily: "PLA",
    colorName: "Beige",
    colorFamily: "Beige",
    colorHex: "#DCCBB6",
    sku: "10201",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PETG Basic",
    materialFamily: "PETG",
    colorName: "Orange",
    colorFamily: "Orange",
    colorHex: "#F46A28",
    sku: "30301",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Matte",
    materialFamily: "PLA",
    colorName: "Matte Terracotta",
    colorFamily: "Brown",
    colorHex: "#C66D48",
    sku: "11203",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Matte",
    materialFamily: "PLA",
    colorName: "Matte Marine Blue",
    colorFamily: "Blue",
    colorHex: "#266A9D",
    sku: "11600",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "Support for PLA/PETG",
    materialFamily: "Support",
    colorName: "Nature",
    colorFamily: "Natural",
    colorHex: "#C8B78D",
    sku: "65102",
    packaging: "With spool",
    initialWeightG: 500,
    count: 2,
  },
  {
    brand: "Bambu Lab",
    productLine: "TPU for AMS",
    materialFamily: "TPU",
    colorName: "Black",
    colorFamily: "Black",
    colorHex: "#1A1B1C",
    sku: "53101",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PET-CF",
    materialFamily: "PET",
    colorName: "Black",
    colorFamily: "Black",
    colorHex: "#252A2D",
    sku: "71100",
    packaging: "With spool",
    initialWeightG: 500,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "ASA",
    materialFamily: "ASA",
    colorName: "White",
    colorFamily: "White",
    colorHex: "#F4F3EE",
    sku: "45100",
    packaging: "With spool",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Basic",
    materialFamily: "PLA",
    colorName: "Pumpkin Orange",
    colorFamily: "Orange",
    colorHex: "#F47B21",
    sku: "10301",
    packaging: "With spool",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Basic",
    materialFamily: "PLA",
    colorName: "Hot Pink",
    colorFamily: "Pink",
    colorHex: "#F15C86",
    sku: "10204",
    packaging: "With spool",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Wood",
    materialFamily: "PLA",
    colorName: "Rosewood",
    colorFamily: "Brown",
    colorHex: "#604033",
    sku: "13204",
    packaging: "With spool",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Wood",
    materialFamily: "PLA",
    colorName: "White Oak",
    colorFamily: "Beige",
    colorHex: "#E3D3B5",
    sku: "13106",
    packaging: "With spool",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Matte",
    materialFamily: "PLA",
    colorName: "Matte Ivory White",
    colorFamily: "White",
    colorHex: "#E9E3D8",
    sku: "11100",
    packaging: "With spool",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PETG Basic",
    materialFamily: "PETG",
    colorName: "Black",
    colorFamily: "Black",
    colorHex: "#18191A",
    sku: "30105",
    packaging: "With spool",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Basic",
    materialFamily: "PLA",
    colorName: "Jade White",
    colorFamily: "White",
    colorHex: "#F3F1E8",
    sku: "10100",
    packaging: "With spool",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Basic",
    materialFamily: "PLA",
    colorName: "Bambu Green",
    colorFamily: "Green",
    colorHex: "#18A76A",
    sku: "10501",
    packaging: "With spool",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Basic",
    materialFamily: "PLA",
    colorName: "Gray",
    colorFamily: "Gray",
    colorHex: "#8C918E",
    sku: "10103",
    packaging: "With spool",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Basic",
    materialFamily: "PLA",
    colorName: "Black",
    colorFamily: "Black",
    colorHex: "#18191A",
    sku: "10101",
    packaging: "With spool",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Basic",
    materialFamily: "PLA",
    colorName: "Red",
    colorFamily: "Red",
    colorHex: "#D93032",
    sku: "10200",
    packaging: "With spool",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Basic",
    materialFamily: "PLA",
    colorName: "Cyan",
    colorFamily: "Blue",
    colorHex: "#1AA6D9",
    sku: "10603",
    packaging: "With spool",
    initialWeightG: 1000,
    count: 1,
  },

];

const additionalProducts = [
  {
    brand: "Bambu Lab",
    productLine: "PLA Basic",
    materialFamily: "PLA",
    colorName: "Black",
    colorFamily: "Black",
    colorHex: "#18191A",
    sku: "10101",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Basic",
    materialFamily: "PLA",
    colorName: "Silver",
    colorFamily: "Silver",
    colorHex: "#A9ADB0",
    sku: "10102",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Basic",
    materialFamily: "PLA",
    colorName: "Blue Grey",
    colorFamily: "Blue",
    colorHex: "#5C6975",
    sku: "10602",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Basic",
    materialFamily: "PLA",
    colorName: "Dark Gray",
    colorFamily: "Gray",
    colorHex: "#484D50",
    sku: "10105",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Matte",
    materialFamily: "PLA",
    colorName: "Matte Ash Gray",
    colorFamily: "Gray",
    colorHex: "#7D858B",
    sku: "11102",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Matte",
    materialFamily: "PLA",
    colorName: "Matte Dark Green",
    colorFamily: "Green",
    colorHex: "#4E623B",
    sku: "11501",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "ABS",
    materialFamily: "ABS",
    colorName: "ABS Black",
    colorFamily: "Black",
    colorHex: "#17191A",
    sku: "40101",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PETG Translucent",
    materialFamily: "PETG",
    colorName: "Translucent Brown",
    colorFamily: "Brown",
    colorHex: "#D4A06D",
    sku: "32800",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PETG Translucent",
    materialFamily: "PETG",
    colorName: "Translucent Orange",
    colorFamily: "Orange",
    colorHex: "#F9A23A",
    sku: "32300",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PETG Translucent",
    materialFamily: "PETG",
    colorName: "Translucent Light Blue",
    colorFamily: "Blue",
    colorHex: "#A9D7EE",
    sku: "32600",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
];

const july13Products = [
  {
    brand: "Bambu Lab",
    productLine: "ABS",
    materialFamily: "ABS",
    colorName: "ABS White",
    colorFamily: "White",
    colorHex: "#F4F2EA",
    sku: "40100",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Basic",
    materialFamily: "PLA",
    colorName: "Beige",
    colorFamily: "Beige",
    colorHex: "#DCCBB6",
    sku: "10201",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Basic",
    materialFamily: "PLA",
    colorName: "Jade White",
    colorFamily: "White",
    colorHex: "#F3F1E8",
    sku: "10100",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 2,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Basic",
    materialFamily: "PLA",
    colorName: "Gold",
    colorFamily: "Gold",
    colorHex: "#D99A1E",
    sku: "10401",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Basic",
    materialFamily: "PLA",
    colorName: "Blue",
    colorFamily: "Blue",
    colorHex: "#1F56B5",
    sku: "10601",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Basic",
    materialFamily: "PLA",
    colorName: "Brown",
    colorFamily: "Brown",
    colorHex: "#8B4B35",
    sku: "10800",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Matte",
    materialFamily: "PLA",
    colorName: "Matte Caramel",
    colorFamily: "Brown",
    colorHex: "#C99762",
    sku: "11803",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PETG Basic",
    materialFamily: "PETG",
    colorName: "Pine Green",
    colorFamily: "Green",
    colorHex: "#1F5A49",
    sku: "30503",
    packaging: "With spool",
    initialWeightG: 1000,
    count: 1,
  },
  {
    brand: "Bambu Lab",
    productLine: "PLA Pure",
    materialFamily: "PLA",
    colorName: "Milky Pink",
    colorFamily: "Pink",
    colorHex: "#F4C7CD",
    sku: "17200",
    packaging: "Refill",
    initialWeightG: 1000,
    count: 1,
  },
];

export const STARTER_DATA_VERSION = 5;
export const JULY_12_PURCHASE_MIGRATION_ID = "starter-purchase-2026-07-12-bambu-10";
export const JULY_13_PURCHASE_MIGRATION_ID = "starter-purchase-2026-07-13-bambu-10";

function makeSeedSpools(
  productList,
  {
    purchasedAt = PURCHASED_AT,
    idPrefix = "seed",
    note = "Imported from purchase screenshots. Confirm that this spool or refill is still on hand.",
  } = {},
) {
  let sequence = 0;
  return productList.flatMap((product) =>
    Array.from({ length: product.count }, (_, index) => {
      sequence += 1;
      const serial = String(index + 1).padStart(2, "0");
      const timestamp = new Date(
        new Date(purchasedAt).getTime() + sequence * 60_000,
      ).toISOString();

      return {
        id: `${idPrefix}-${product.sku}-${product.packaging === "Refill" ? "r" : "s"}-${serial}`,
        brand: product.brand,
        productLine: product.productLine,
        materialFamily: product.materialFamily,
        colorName: product.colorName,
        colorFamily: product.colorFamily,
        colorHex: product.colorHex,
        sku: product.sku,
        productUrl: "",
        packaging: product.packaging,
        initialWeightG: product.initialWeightG,
        remainingWeightG: product.initialWeightG,
        reorderAtG: product.initialWeightG <= 500 ? 100 : 250,
        status: "Needs audit",
        location: "Unassigned",
        notes: note,
        verified: false,
        addedAt: timestamp,
        updatedAt: timestamp,
      };
    }),
  );
}

export const INITIAL_SEED_SPOOLS = makeSeedSpools(originalProducts);

export const STARTER_V2_SPOOLS = makeSeedSpools(additionalProducts, {
  purchasedAt: "2026-07-12T19:25:00.000Z",
  idPrefix: "seed-v2",
  note: "Imported from the additional Bambu Lab purchase screenshot dated 2026-07-12. Confirm that this spool or refill is still on hand.",
});

export const STARTER_V4_SPOOLS = makeSeedSpools(july13Products, {
  purchasedAt: "2026-07-13T17:08:00.000Z",
  idPrefix: "seed-v4",
  note: "Imported from the Bambu Lab purchase screenshot supplied on 2026-07-13. Confirm that this spool or refill is still on hand.",
});

export const SEED_SPOOLS = [
  ...INITIAL_SEED_SPOOLS,
  ...STARTER_V2_SPOOLS,
  ...STARTER_V4_SPOOLS,
];

export const DEFAULT_INVENTORY = {
  schemaVersion: 1,
  starterDataVersion: STARTER_DATA_VERSION,
  appliedMigrations: [
    JULY_12_PURCHASE_MIGRATION_ID,
    JULY_13_PURCHASE_MIGRATION_ID,
  ],
  spools: SEED_SPOOLS,
  events: [
    {
      id: "seed-event-1",
      type: "import",
      message: "Started with 36 purchased spools from the supplied Bambu Lab order screenshots.",
      createdAt: "2026-07-11T21:00:00.000Z",
    },
    {
      id: "seed-event-2",
      type: "import",
      message: "Added 10 purchased spools from the Bambu Lab order screenshot supplied on 2026-07-12.",
      createdAt: "2026-07-12T19:40:00.000Z",
    },
    {
      id: "seed-event-3",
      type: "import",
      message: "Added 10 purchased spools from the Bambu Lab order screenshot supplied on 2026-07-13.",
      createdAt: "2026-07-13T17:10:00.000Z",
    },
  ],
  settings: {
    viewMode: "products",
    displayMode: "cards",
    theme: "system",
  },
};
